function [data, m] = generate_data_step(means1, means2, cov1, cov2, ...
                                len1, len2, len3 )
                            
data = [mvnrnd(means1, cov1, len1)', ...
        mvnrnd(means2, cov2, len2)', ...
        mvnrnd(means1, cov1, len3)'];
    
m = [repmat(means1', 1, len1), ...
     repmat(means2', 1, len2), ...
     repmat(means1', 1, len3)];
end

